---
# This configuration file can be used to run the MVPA analysis with the fmri_decoder 
# package.


# parameters
# ---

# data preprocessing parameters
TR: 3  # repetition time in seconds
n_skip: 2  # number of skipped initial volumes per experimental condition*
cutoff_sec: 270  # cutoff frequency for time series detrending in 1/Hz
filter_size: 0.5  # bandpass filter size (applied if not none)**
# *Time series volumes are skipped at the beginning of each experimental block to 
# disregard transient BOLD responses from further analysis.
# **After sampling time series data onto the surface geometry, the sampled data can 
# optionally be filtered using a bandpass filter (Laplacian of Gaussian). The filter 
# size is the size of the gaussian filter as described in Chen et al., Neuroimage, 181, 
# 2018.

# model parameters
nmax: 200  # number of selected features (applied if not none)
radius: 1.6  # minimum radius between selected features in mm (applied if not none)
feature_scaling: standard  # feature scaling method: min_max | standard | none
sample_scaling: none  # sample normalization method: norm | standard | none


# data
# ---

# Realigned fmri time series. It is expected that individual time series are aligned to
# each other.
file_series:
  - /home/daniel/ownCloud/data/func/run_1.nii
  - /home/daniel/ownCloud/data/func/run_2.nii
  - /home/daniel/ownCloud/data/func/run_3.nii
  - /home/daniel/ownCloud/data/func/run_4.nii
  - /home/daniel/ownCloud/data/func/run_5.nii
  - /home/daniel/ownCloud/data/func/run_6.nii
  - /home/daniel/ownCloud/data/func/run_7.nii
  - /home/daniel/ownCloud/data/func/run_8.nii
  - /home/daniel/ownCloud/data/func/run_9.nii
  - /home/daniel/ownCloud/data/func/run_10.nii

# Corresponding condition files. Events of each experimental condition (onsets, names, 
# durations) are expected to be saved as a cell array in a .mat file format that is 
# comptible with SPM12.*
file_events:
  - /home/daniel/ownCloud/data/func/run_1_events.mat
  - /home/daniel/ownCloud/data/func/run_2_events.mat
  - /home/daniel/ownCloud/data/func/run_3_events.mat
  - /home/daniel/ownCloud/data/func/run_4_events.mat
  - /home/daniel/ownCloud/data/func/run_5_events.mat
  - /home/daniel/ownCloud/data/func/run_6_events.mat
  - /home/daniel/ownCloud/data/func/run_7_events.mat
  - /home/daniel/ownCloud/data/func/run_8_events.mat
  - /home/daniel/ownCloud/data/func/run_9_events.mat
  - /home/daniel/ownCloud/data/func/run_10_events.mat
  # *To be more precise, each .mat file must contain three cell arrays (onsets, names,
  # durations) of shape 1x3. The first column is expected to contain the baseline
  # condition which will be discarded. The remaining columns contain the experimental
  # conditions that are used for binary classification.

# FreeSurfer geometries for multiple cortical depths. Single hemispheres are given
# independently. Analyses will be performed for each provided cortical surface.
file_layer:
  lh:
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_0
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_1
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_2
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_3
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_4
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_5
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_6
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_7
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_8
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_9
    - /home/daniel/ownCloud/data/ana/surf/lh.layer_10
  rh:
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_0
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_1
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_2
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_3
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_4
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_5
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_6
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_7
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_8
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_9
    - /home/daniel/ownCloud/data/ana/surf/rh.layer_10

# A coordinate mapping that contains the transformation of surface coordinates to the
# the space of fmri time series. This deformation file is optional and should be only
# given if surface and volume data are not aligned to each other (used if not none).*
file_deformation: /home/daniel/ownCloud/data/ana/deform/transformation.nii.gz
# *see https://github.com/haenelt/FmriTools/blob/master/fmri_tools/cmap/generate_coordinate_mapping.py
# for comparison

# MGH surface overlays for feature selection.* Data points are selected by their 
# magnitude in the localizer overlay. When mutliple files are given, the average across 
# overlays is first computed. Single hemispheres are given independently.
file_localizer:
  lh:
    - /home/daniel/ownCloud/data/loc/lh.localizer1.mgh
    - /home/daniel/ownCloud/data/loc/lh.localizer2.mgh
  rh:
    - /home/daniel/ownCloud/data/loc/rh.localizer1.mgh
    - /home/daniel/ownCloud/data/loc/rh.localizer2.mgh
# *if set to none/None, no feature selection is performed based on an independent data 
# set. If nmax is still selected, feature selection will be based on ANOVA F-values of 
# the training data set and the best nmax features will be taken.

# FreeSurfer .label files to restrict data analysis to one cortical area (e.g. V1). When 
# multiple files are given, the intersection of all labels is taken. Single hemispheres 
# are given independently.
file_label:
  lh:
    - /home/daniel/ownCloud/data/ana/label/lh.v1.label
    - /home/daniel/ownCloud/data/ana/label/lh.fov.label
  rh:
    - /home/daniel/ownCloud/data/ana/label/rh.v1.label
    - /home/daniel/ownCloud/data/ana/label/rh.fov.label
